/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteIndexRouteImport } from './routes/invite.index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedVitalsRouteImport } from './routes/_authenticated/vitals'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated/shopping'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedOxygenRouteImport } from './routes/_authenticated/oxygen'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInstructionsRouteImport } from './routes/_authenticated/instructions'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHandoverRouteImport } from './routes/_authenticated/handover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChildRouteImport } from './routes/_authenticated/child'
import { Route as AuthenticatedCaregiversRouteImport } from './routes/_authenticated/caregivers'
import { Route as AuthenticatedOnboardingChildRouteImport } from './routes/_authenticated/onboarding.child'
import { Route as AuthenticatedOnboardingCaregiverRouteImport } from './routes/_authenticated/onboarding.caregiver'
import { Route as ApiPublicHooksDispatchTaskNotificationsRouteImport } from './routes/api/public/hooks/dispatch-task-notifications'
import { Route as ApiPublicHooksCarePlaceMissedSweepRouteImport } from './routes/api/public/hooks/care-place-missed-sweep'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedVitalsRoute = AuthenticatedVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOxygenRoute = AuthenticatedOxygenRouteImport.update({
  id: '/oxygen',
  path: '/oxygen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstructionsRoute =
  AuthenticatedInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHandoverRoute = AuthenticatedHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChildRoute = AuthenticatedChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaregiversRoute = AuthenticatedCaregiversRouteImport.update({
  id: '/caregivers',
  path: '/caregivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingChildRoute =
  AuthenticatedOnboardingChildRouteImport.update({
    id: '/onboarding/child',
    path: '/onboarding/child',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingCaregiverRoute =
  AuthenticatedOnboardingCaregiverRouteImport.update({
    id: '/onboarding/caregiver',
    path: '/onboarding/caregiver',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksDispatchTaskNotificationsRoute =
  ApiPublicHooksDispatchTaskNotificationsRouteImport.update({
    id: '/api/public/hooks/dispatch-task-notifications',
    path: '/api/public/hooks/dispatch-task-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCarePlaceMissedSweepRoute =
  ApiPublicHooksCarePlaceMissedSweepRouteImport.update({
    id: '/api/public/hooks/care-place-missed-sweep',
    path: '/api/public/hooks/care-place-missed-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/caregivers': typeof AuthenticatedCaregiversRoute
  '/child': typeof AuthenticatedChildRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handover': typeof AuthenticatedHandoverRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/instructions': typeof AuthenticatedInstructionsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/oxygen': typeof AuthenticatedOxygenRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/invite/$code': typeof InviteCodeRoute
  '/invite/': typeof InviteIndexRoute
  '/onboarding/caregiver': typeof AuthenticatedOnboardingCaregiverRoute
  '/onboarding/child': typeof AuthenticatedOnboardingChildRoute
  '/api/public/hooks/care-place-missed-sweep': typeof ApiPublicHooksCarePlaceMissedSweepRoute
  '/api/public/hooks/dispatch-task-notifications': typeof ApiPublicHooksDispatchTaskNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/caregivers': typeof AuthenticatedCaregiversRoute
  '/child': typeof AuthenticatedChildRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handover': typeof AuthenticatedHandoverRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/instructions': typeof AuthenticatedInstructionsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/oxygen': typeof AuthenticatedOxygenRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/invite/$code': typeof InviteCodeRoute
  '/invite': typeof InviteIndexRoute
  '/onboarding/caregiver': typeof AuthenticatedOnboardingCaregiverRoute
  '/onboarding/child': typeof AuthenticatedOnboardingChildRoute
  '/api/public/hooks/care-place-missed-sweep': typeof ApiPublicHooksCarePlaceMissedSweepRoute
  '/api/public/hooks/dispatch-task-notifications': typeof ApiPublicHooksDispatchTaskNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/caregivers': typeof AuthenticatedCaregiversRoute
  '/_authenticated/child': typeof AuthenticatedChildRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/handover': typeof AuthenticatedHandoverRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/instructions': typeof AuthenticatedInstructionsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/medications': typeof AuthenticatedMedicationsRoute
  '/_authenticated/oxygen': typeof AuthenticatedOxygenRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRoute
  '/_authenticated/vitals': typeof AuthenticatedVitalsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/invite/$code': typeof InviteCodeRoute
  '/invite/': typeof InviteIndexRoute
  '/_authenticated/onboarding/caregiver': typeof AuthenticatedOnboardingCaregiverRoute
  '/_authenticated/onboarding/child': typeof AuthenticatedOnboardingChildRoute
  '/api/public/hooks/care-place-missed-sweep': typeof ApiPublicHooksCarePlaceMissedSweepRoute
  '/api/public/hooks/dispatch-task-notifications': typeof ApiPublicHooksDispatchTaskNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/caregivers'
    | '/child'
    | '/dashboard'
    | '/handover'
    | '/home'
    | '/insights'
    | '/instructions'
    | '/inventory'
    | '/medications'
    | '/oxygen'
    | '/schedule'
    | '/settings'
    | '/shifts'
    | '/shopping'
    | '/vitals'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/invite/$code'
    | '/invite/'
    | '/onboarding/caregiver'
    | '/onboarding/child'
    | '/api/public/hooks/care-place-missed-sweep'
    | '/api/public/hooks/dispatch-task-notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/caregivers'
    | '/child'
    | '/dashboard'
    | '/handover'
    | '/home'
    | '/insights'
    | '/instructions'
    | '/inventory'
    | '/medications'
    | '/oxygen'
    | '/schedule'
    | '/settings'
    | '/shifts'
    | '/shopping'
    | '/vitals'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/invite/$code'
    | '/invite'
    | '/onboarding/caregiver'
    | '/onboarding/child'
    | '/api/public/hooks/care-place-missed-sweep'
    | '/api/public/hooks/dispatch-task-notifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/caregivers'
    | '/_authenticated/child'
    | '/_authenticated/dashboard'
    | '/_authenticated/handover'
    | '/_authenticated/home'
    | '/_authenticated/insights'
    | '/_authenticated/instructions'
    | '/_authenticated/inventory'
    | '/_authenticated/medications'
    | '/_authenticated/oxygen'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/_authenticated/shopping'
    | '/_authenticated/vitals'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/invite/$code'
    | '/invite/'
    | '/_authenticated/onboarding/caregiver'
    | '/_authenticated/onboarding/child'
    | '/api/public/hooks/care-place-missed-sweep'
    | '/api/public/hooks/dispatch-task-notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InviteCodeRoute: typeof InviteCodeRoute
  InviteIndexRoute: typeof InviteIndexRoute
  ApiPublicHooksCarePlaceMissedSweepRoute: typeof ApiPublicHooksCarePlaceMissedSweepRoute
  ApiPublicHooksDispatchTaskNotificationsRoute: typeof ApiPublicHooksDispatchTaskNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InviteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/vitals': {
      id: '/_authenticated/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AuthenticatedVitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oxygen': {
      id: '/_authenticated/oxygen'
      path: '/oxygen'
      fullPath: '/oxygen'
      preLoaderRoute: typeof AuthenticatedOxygenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructions': {
      id: '/_authenticated/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof AuthenticatedInstructionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/handover': {
      id: '/_authenticated/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof AuthenticatedHandoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/child': {
      id: '/_authenticated/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof AuthenticatedChildRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregivers': {
      id: '/_authenticated/caregivers'
      path: '/caregivers'
      fullPath: '/caregivers'
      preLoaderRoute: typeof AuthenticatedCaregiversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/child': {
      id: '/_authenticated/onboarding/child'
      path: '/onboarding/child'
      fullPath: '/onboarding/child'
      preLoaderRoute: typeof AuthenticatedOnboardingChildRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/caregiver': {
      id: '/_authenticated/onboarding/caregiver'
      path: '/onboarding/caregiver'
      fullPath: '/onboarding/caregiver'
      preLoaderRoute: typeof AuthenticatedOnboardingCaregiverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/dispatch-task-notifications': {
      id: '/api/public/hooks/dispatch-task-notifications'
      path: '/api/public/hooks/dispatch-task-notifications'
      fullPath: '/api/public/hooks/dispatch-task-notifications'
      preLoaderRoute: typeof ApiPublicHooksDispatchTaskNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/care-place-missed-sweep': {
      id: '/api/public/hooks/care-place-missed-sweep'
      path: '/api/public/hooks/care-place-missed-sweep'
      fullPath: '/api/public/hooks/care-place-missed-sweep'
      preLoaderRoute: typeof ApiPublicHooksCarePlaceMissedSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCaregiversRoute: typeof AuthenticatedCaregiversRoute
  AuthenticatedChildRoute: typeof AuthenticatedChildRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHandoverRoute: typeof AuthenticatedHandoverRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInstructionsRoute: typeof AuthenticatedInstructionsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRoute
  AuthenticatedOxygenRoute: typeof AuthenticatedOxygenRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRoute
  AuthenticatedVitalsRoute: typeof AuthenticatedVitalsRoute
  AuthenticatedOnboardingCaregiverRoute: typeof AuthenticatedOnboardingCaregiverRoute
  AuthenticatedOnboardingChildRoute: typeof AuthenticatedOnboardingChildRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCaregiversRoute: AuthenticatedCaregiversRoute,
  AuthenticatedChildRoute: AuthenticatedChildRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHandoverRoute: AuthenticatedHandoverRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInstructionsRoute: AuthenticatedInstructionsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRoute,
  AuthenticatedOxygenRoute: AuthenticatedOxygenRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRoute,
  AuthenticatedVitalsRoute: AuthenticatedVitalsRoute,
  AuthenticatedOnboardingCaregiverRoute: AuthenticatedOnboardingCaregiverRoute,
  AuthenticatedOnboardingChildRoute: AuthenticatedOnboardingChildRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InviteCodeRoute: InviteCodeRoute,
  InviteIndexRoute: InviteIndexRoute,
  ApiPublicHooksCarePlaceMissedSweepRoute:
    ApiPublicHooksCarePlaceMissedSweepRoute,
  ApiPublicHooksDispatchTaskNotificationsRoute:
    ApiPublicHooksDispatchTaskNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
